[package]
name = "munkres"
version = "0.3.0"
authors = ["Michael Neumann <mneumann@ntecs.de>"]
license = "BSD-3-Clause"
repository = "https://github.com/mneumann/munkres-rs"
description = "Kuhn-Munkres (aka Hungarian) algorithm for solving the Assignment Problem with O(n^3) time complexity"
keywords = ["algorithm", "optimization"]
include = ["src/*.rs", "Cargo.toml", "LICENSE", "README.md"]

[dependencies]
fixedbitset = "0.1"
ndarray = "0.11"
